<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RootNamespace>SASD.LearningManager.WinForms</RootNamespace>
    <AssemblyName>SASD.LearningManager</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SASD.LearningManager.Application\SASD.LearningManager.Application.csproj" />
    <ProjectReference Include="..\SASD.LearningManager.Infrastructure\SASD.LearningManager.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>
</Project>
