<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SASD.LearningManager.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SASD.LearningManager.Domain\SASD.LearningManager.Domain.csproj" />
  </ItemGroup>
</Project>
