using Microsoft.Data.Sqlite;
using SASD.LearningManager.Application.Common;
using SASD.LearningManager.Application.Evidence;
using SASD.LearningManager.Domain.Evidence;

namespace SASD.LearningManager.Infrastructure.Persistence.Repositories;

/// <summary>SQLite persistence for user-controlled competency evidence.</summary>
public sealed class EvidenceRepository : IEvidenceRepository
{
    private readonly SqliteConnectionFactory _connections;
    public EvidenceRepository(SqliteConnectionFactory connections) => _connections = connections;
    public async Task<EvidenceItem?> GetByIdAsync(Guid id,CancellationToken ct=default) { await using var c=await _connections.OpenAsync(ct);await using var q=c.CreateCommand();q.CommandText="SELECT Id,Title,Description,Type,OccurredAtUtc,Url,LocalPath,Evaluation,Status,CreatedAtUtc,UpdatedAtUtc,ArchivedAtUtc FROM Evidence WHERE Id=$id;";q.Parameters.AddWithValue("$id",id.ToString("D"));await using var r=await q.ExecuteReaderAsync(ct);return await r.ReadAsync(ct)?Map(r):null; }
    public async Task<EvidenceDetailDto?> GetDetailAsync(Guid id,CancellationToken ct=default) { var x=await GetByIdAsync(id,ct);if(x is null)return null;await using var c=await _connections.OpenAsync(ct);return new(x.Id,x.Title,x.Description,x.Type,x.OccurredAtUtc,x.Url,x.LocalPath,x.Evaluation,x.Status,x.CreatedAtUtc,x.UpdatedAtUtc,await Links(c,"EvidenceSkills","SkillId",id,ct),await Links(c,"EvidenceResources","ResourceId",id,ct),await Links(c,"EvidenceGoals","GoalId",id,ct)); }
    public async Task<PagedResult<EvidenceListItemDto>> SearchAsync(EvidenceSearchCriteria x,CancellationToken ct=default) { await using var c=await _connections.OpenAsync(ct);var where=x.IncludeArchived?"1=1":"e.Status <> 'Archived'";if(!string.IsNullOrWhiteSpace(x.SearchText))where+=" AND (e.Title LIKE $search ESCAPE '\\' COLLATE NOCASE OR e.Description LIKE $search ESCAPE '\\' COLLATE NOCASE)";if(x.SkillId is not null)where+=" AND EXISTS(SELECT 1 FROM EvidenceSkills es WHERE es.EvidenceId=e.Id AND es.SkillId=$skill)";await using var count=c.CreateCommand();count.CommandText=$"SELECT COUNT(1) FROM Evidence e WHERE {where};";Params(count,x);var total=Convert.ToInt32(await count.ExecuteScalarAsync(ct),System.Globalization.CultureInfo.InvariantCulture);await using var q=c.CreateCommand();q.CommandText=$"SELECT e.Id,e.Title,e.Type,e.OccurredAtUtc,e.Status,(SELECT COUNT(1) FROM EvidenceSkills es WHERE es.EvidenceId=e.Id) FROM Evidence e WHERE {where} ORDER BY e.OccurredAtUtc DESC LIMIT $limit OFFSET $offset;";Params(q,x);q.Parameters.AddWithValue("$limit",x.PageSize);q.Parameters.AddWithValue("$offset",(x.PageNumber-1)*x.PageSize);var list=new List<EvidenceListItemDto>();await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(new(Guid.Parse(r.GetString(0)),r.GetString(1),Enum.Parse<EvidenceType>(r.GetString(2)),SqliteValue.DateTimeOffset(r,3),Enum.Parse<EvidenceStatus>(r.GetString(4)),r.GetInt32(5)));return new(list,x.PageNumber,x.PageSize,total); }
    public async Task SaveAsync(EvidenceItem x,EvidenceEditModel model,bool insert,CancellationToken ct=default) { await using var c=await _connections.OpenAsync(ct);using var tx=c.BeginTransaction();try{await using(var q=c.CreateCommand()){q.Transaction=tx;q.CommandText=insert?"INSERT INTO Evidence(Id,Title,Description,Type,OccurredAtUtc,Url,LocalPath,Evaluation,Status,CreatedAtUtc,UpdatedAtUtc,ArchivedAtUtc) VALUES($id,$title,$description,$type,$occurred,$url,$path,$evaluation,$status,$created,$updated,$archived);":"UPDATE Evidence SET Title=$title,Description=$description,Type=$type,OccurredAtUtc=$occurred,Url=$url,LocalPath=$path,Evaluation=$evaluation,Status=$status,UpdatedAtUtc=$updated,ArchivedAtUtc=$archived WHERE Id=$id;";q.Parameters.AddWithValue("$id",x.Id.ToString("D"));q.Parameters.AddWithValue("$title",x.Title);q.Parameters.AddWithValue("$description",SqliteValue.ToDb(x.Description));q.Parameters.AddWithValue("$type",x.Type.ToString());q.Parameters.AddWithValue("$occurred",SqliteValue.ToDb(x.OccurredAtUtc));q.Parameters.AddWithValue("$url",SqliteValue.ToDb(x.Url));q.Parameters.AddWithValue("$path",SqliteValue.ToDb(x.LocalPath));q.Parameters.AddWithValue("$evaluation",SqliteValue.ToDb(x.Evaluation));q.Parameters.AddWithValue("$status",x.Status.ToString());q.Parameters.AddWithValue("$created",SqliteValue.ToDb(x.CreatedAtUtc));q.Parameters.AddWithValue("$updated",SqliteValue.ToDb(x.UpdatedAtUtc));q.Parameters.AddWithValue("$archived",SqliteValue.ToDb(x.ArchivedAtUtc));if(await q.ExecuteNonQueryAsync(ct)!=1)throw new InvalidOperationException("Evidence could not be saved.");}await Replace(c,tx,"EvidenceSkills","SkillId",x.Id,model.SkillIds,ct);await Replace(c,tx,"EvidenceResources","ResourceId",x.Id,model.ResourceIds,ct);await Replace(c,tx,"EvidenceGoals","GoalId",x.Id,model.GoalIds,ct);await tx.CommitAsync(ct);}catch{await tx.RollbackAsync(CancellationToken.None);throw;} }
    private static EvidenceItem Map(SqliteDataReader r)=>EvidenceItem.Rehydrate(Guid.Parse(r.GetString(0)),r.GetString(1),SqliteValue.NullableString(r,2),Enum.Parse<EvidenceType>(r.GetString(3)),SqliteValue.DateTimeOffset(r,4),SqliteValue.NullableString(r,5),SqliteValue.NullableString(r,6),SqliteValue.NullableString(r,7),Enum.Parse<EvidenceStatus>(r.GetString(8)),SqliteValue.DateTimeOffset(r,9),SqliteValue.DateTimeOffset(r,10),SqliteValue.NullableDateTimeOffset(r,11));
    private static void Params(SqliteCommand q,EvidenceSearchCriteria x){if(!string.IsNullOrWhiteSpace(x.SearchText))q.Parameters.AddWithValue("$search",$"%{x.SearchText.Trim().Replace("\\","\\\\",StringComparison.Ordinal).Replace("%","\\%",StringComparison.Ordinal).Replace("_","\\_",StringComparison.Ordinal)}%");if(x.SkillId is not null)q.Parameters.AddWithValue("$skill",x.SkillId.Value.ToString("D"));}
    private static async Task<IReadOnlyList<Guid>> Links(SqliteConnection c,string table,string column,Guid id,CancellationToken ct){await using var q=c.CreateCommand();q.CommandText=$"SELECT {column} FROM {table} WHERE EvidenceId=$id ORDER BY {column};";q.Parameters.AddWithValue("$id",id.ToString("D"));var list=new List<Guid>();await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(Guid.Parse(r.GetString(0)));return list;}
    private static async Task Replace(SqliteConnection c,SqliteTransaction tx,string table,string column,Guid id,IEnumerable<Guid> ids,CancellationToken ct){await using(var d=c.CreateCommand()){d.Transaction=tx;d.CommandText=$"DELETE FROM {table} WHERE EvidenceId=$id;";d.Parameters.AddWithValue("$id",id.ToString("D"));await d.ExecuteNonQueryAsync(ct);}foreach(var value in ids.Distinct()){await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText=$"INSERT INTO {table}(EvidenceId,{column}) VALUES($id,$value);";q.Parameters.AddWithValue("$id",id.ToString("D"));q.Parameters.AddWithValue("$value",value.ToString("D"));await q.ExecuteNonQueryAsync(ct);}}
}
